accounts/urls.py
from django.urls import path
from .views import *

app_name = 'accounts'

urlpatterns = [
    path('signup/', signup, name='signup'),
    path('login/', login_check, name='login'),
    path('logout/', logout, name='logout'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from main.views import index, program

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('program/', program, name='program'),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('community/', include('community.urls')),
]

accounts/models.py
from django.db import models
from django.conf import settings # 인증 관련 패키지 사용을 위한 import
from django.core.validators import RegexValidator

# Create your models here.

class Profile(models.Model):
    # settings의 AUTH_USER_MODEL의 필드와 1대1 대응해서 사용
    # user_id
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # 이름
    user_name = models.CharField('이름', max_length=10)
    # 생년월일
    birth_date = models.DateField('date published')
    # 성별
    Gender = (
        ('성별', '성별'),
        ('남성', '남성'),
        ('여성', '여성'),
    )
    gender = models.CharField('성별',
                              max_length=10,
                              choices=Gender,
                              default='N')

    # E-mail : 선택사항
    email = models.EmailField(verbose_name='본인 확인 이메일(선택사항)',
                              max_length=128,
                              blank=True)
    # 휴대전화 번호
    phone_number = models.CharField(max_length=20, validators=[RegexValidator(r'^010[1-9]\d{7}$')])

    def __str__(self):
        return self.user_name

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Profile
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User

class LoginForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["username", "password"]

class SignupForm(UserCreationForm):
    username = forms.CharField(label='아이디', widget=forms.TextInput(attrs={
        'pattern': '[a-zA-Z0-9]+',
        'title': '특수문자, 공백 입력 불가',
    }))
    user_name = forms.CharField(label='이름')
    phone_number = forms.CharField(label='핸드폰 번호')
    Gender = (
        ('성별', '성별'),
        ('남성', '남성'),
        ('여성', '여성'),
    )
    gender = forms.ChoiceField(label='성별', choices=Gender)
    birth_date = forms.DateField(label='생년월일')

    class Meta(UserCreationForm.Meta):
        fields = UserCreationForm.Meta.fields + ('email',)

    def clean_phone_number(self):
        phone_number = self.cleaned_data.get('phone_number')
        if Profile.objects.filter(phone_number=phone_number).exists():
            raise forms.ValidationError('동일한 번호가 이미 존재합니다.')
        return phone_number

    def clean_email(self):
        email = self.cleaned_data.get('email')
        User = get_user_model()
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('사용중인 이메일입니다.')
        return email

    def save(self):
        user = super().save()
        Profile.objects.create(
            user=user,
            user_name=self.cleaned_data['user_name'],
            birth_date=self.cleaned_data['birth_date'],
            gender=self.cleaned_data['gender'],
            email=self.cleaned_data['email'],
            phone_number=self.cleaned_data['phone_number'],
        )
        return user

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login # 로그인 기능을 하는 패키지 함수
from django.contrib.auth import logout as django_logout
from .forms import SignupForm, LoginForm # forms.py를 생성해서 SignupForm, LoginForm 정의해서 사용.

# Create your views here.

def signup(request):
    if request.method == "POST":
        form = SignupForm(request.POST)

        if form.is_valid():
            user = form.save()
            return redirect('accounts:login')
    else:
        form = SignupForm()

    return render(request, 'accounts/signup.html', {
        'form': form,
    })

def login_check(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        name = request.POST.get('username')
        pwd = request.POST.get('password')

        user = authenticate(username=name, password=pwd)

        if user is not None:
            login(request, user)
            return redirect("/")
        else:
            return render(request, 'accounts/login_fail.html')
    else:
        form = LoginForm()
        return render(request, 'accounts/login.html', {
            'form': form
        })

def logout(request):
    django_logout(request)
    return redirect("/")

templates/accounts/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>로그인</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <link rel="stylesheet" href="{% static 'css/signup.css' %}">
    <!-- jQuery JS -->
    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    <!-- Bootstrap JS -->
    <script src="{% static 'bootstrap.min.js' %}"></script>
</head>
<body>
<div id="wrap">
    <div id="header">
        <h1>
            <a href="https://www.naver.com" class="logo" id="naverlogo">
                <span class="blind">NAVER</span>
            </a>
        </h1>
    </div>
    {% block content %}

    {% endblock %}
</div>
</body>
</html>

templates/accounts/login.html
{% extends "accounts/layout.html" %}

{% block content %}
<div id="container">
    <div class="form">
        <form action="{% url 'accounts:login' %}" method="post">
            {% csrf_token %}
            <p class="login_user_name">
                <input id="{{form.username.id_for_label}}" name="{{form.username.html_name}}" placeholder="아이디">
            </p>
            <p class="login_user_password">
                <input type="password" id="{{form.password.id_for_label}}" name="{{form.password.html_name}}" placeholder="비밀번호">
            </p>
            <input type="submit" id="submit_btn" value="로그인" class="submit_btn">
        </form>
    </div>
</div>
<div class="bottom_box">
    <div id="bottom">
        <a href="{% url 'accounts:signup'%}">회원가입</a>
    </div>
</div>
{% endblock %}

templates/accounts/login_fail.html
{% extends "accounts/layout.html" %}

{% block content %}
<div id="container">
    <div class="form">
        <form action="#" method="post">
            <p class="login_user_name">
                <input id="id" placeholder="아이디">
            </p>
            <p class="login_user_password">
                <input type="password" id="#" placeholder="비밀번호">
            </p>
            <p style="color: red;">
                가입하지 않은 아이디이거나, 잘못된 비밀번호입니다.
            </p>
            <input type="submit" id="submit_btn" value="로그인" class="submit_btn">
        </form>
    </div>
</div>
<div class="bottom_box">
    <div id="bottom">
        <a href="{% url 'accounts:signup'%}">회원가입</a>
    </div>
</div>
{% endblock %}

templates/accounts/signup.html
{% extends "accounts/layout.html" %}

{% block content %}
<div id="container">
    <div class="form_container">
        <div class="form">
            <form method="post">
                {% csrf_token %}
                {% include "form_errors.html" %}
                    <p>
                        <h3><label for="id_username">아이디</label></h3>
                        <input type="text" name="username" pattern="[a-zA-Z0-9]+" title="특수문자, 공백 입력 불가" autofocus="" required="" id="{{form.username.id_for_label}}">
                    </p>
                    <p>
                        <h3><label for="id_email">이메일 주소</label></h3>
                        <input type="email" name="email" maxlength="254" id="{{form.email.id_for_label}}">
                    </p>
                    <p>
                        <h3><label for="id_password1">비밀번호</label></h3>
                        <input type="password" name="password1" autocomplete="new-password" required="" id="{{form.password1.id_for_label}}">
                    </p>
                    <p>
                        <h3><label for="id_password2">비밀번호 확인</label></h3>
                        <input type="password" name="password2" autocomplete="new-password" required="" id="{{form.password2.id_for_label}}">
                    </p>
                    <p>
                        <h3><label for="id_user_name">이름</label></h3>
                        <input type="text" name="user_name" required="" id="{{form.user_name.id_for_label}}">
                    </p>
                    <p>
                        <h3><label for="id_phone_number">핸드폰 번호</label></h3>
                        <input type="text" name="phone_number" required="" id="{{form.phone_number.id_for_label}}" placeholder="'-'를 제외한 숫자 11자리">
                    </p>
                    <p>
                        <h3><label for="id_gender">성별</label></h3>
                        <select name="gender" id="{{form.gender.id_for_label}}">
                            <option value="성별">성별</option>
                            <option value="여성">여성</option>
                            <option value="남성">남성</option>
                        </select>
                    </p>
                    <p>
                        <h3><label for="id_birth_date">생년월일:</label></h3>
                        <input type="text" name="birth_date" required="" id="{{form.birth_date.id_for_label}}" placeholder="EX)YYYY-MM-DD">
                    </p>
                <input type="submit" id="submit_btn" value="회원가입" class="submit_btn">
            </form>
        </div>
    </div>
</div>
<div class="bottom_box">
    <div id="bottom">
        <span>아이디가 있으신가요? </span>
        <a href="{% url 'accounts:login'%}">로그인</a>
    </div>
</div>
{% endblock %}