accounts/urls.py
from django.urls import path
from .views import *

app_name = 'accounts'

urlpatterns = [
    path('signup/', signup, name='signup'),
    path('login/', login_check, name='login'),
    path('logout/', logout, name='logout'),
]

community/urls.py
from django.urls import path
from .views import *

app_name = 'community'

urlpatterns = [
    path('', forum, name='forum'),
    path('<int:question_id>', detail, name='detail'),
    path('answer/create/<int:question_id>',  answer_create, name='answer_create'),
    path('question/create/', question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_delete, name='question_delete'),
    path('answer/modify/<int:answer_id>/', answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_delete, name='answer_delete')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from main.views import index, program

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('program/', program, name='program'),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('community/', include('community.urls')),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'main/index.html')

def program(request):
    return render(request, 'main/program.html')

templates/main/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
{% load static %}
    <meta charset="UTF-8">
    <title>NAVER_D2_CloneCoding</title>
    <link rel="stylesheet" type="text/css" href="{%static 'css/article.css'%}">
    <link rel="stylesheet" type="text/css" href="{%static 'css/sidebar.css'%}">
    <link rel="stylesheet" type="text/css" href="{%static 'css/paginate.css'%}">
    <link rel="stylesheet" href="{%static 'css/common.css'%}">
    <link rel="stylesheet" href="{%static 'css/index.css'%}">
    <link rel="stylesheet" href="{%static 'css/slideShow.css'%}">
    <link rel="stylesheet" href="{%static 'css/footer.css' %}">
    <link rel="stylesheet" href="{%static 'css/forum.css' %}">
    <link rel="stylesheet" href="{%static 'css/proMain.css' %}">
    <link rel="stylesheet" href="{%static 'css/contentbox.css' %}">
    <link rel="stylesheet" href="{%static 'css/content.css' %}">
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/xeicon@2.3.3/xeicon.min.css">
    <script src="{%static 'js/jquery-3.5.1.min.js' %}"></script>
    <script src="{%static 'js/index.js' %}"></script>
    <script src="{%static 'js/slideShow.js'%}"></script>
    <style>
        @media (max-width:767px){
            .sidebar{
                position: relative;
                width:100%;
                height:100%;
            }
            .sidebar .Top5 {
                margin-bottom: 21px;
                padding: 15px 0 11px;
            }
        }
    </style>
</head>
<body>
    <div id="wrap">
        <header>
            <div id="headerBox">
                <div class="main_lnb">
                    <div id="logoBox" onclick="location.href='{% url 'index' %}'"></div>
                    <div id="topMenuBox">
                        <a>Hello world</a>
                        <a>D2 News</a>
                        <a href="{% url 'program' %}">D2 Program</a>
                        <a href="{% url 'community:forum' %}">Forum</a>
                        {% if user.is_authenticated %}
                            <a href="{% url 'accounts:logout' %}">로그아웃</a>
                        {% else %}
                            <a href="{% url 'accounts:login'%}">로그인</a>
                        {% endif %}
                    </div>
                    <div id="inputBox">
                        <input type="text" placeholder="D2에서 검색">
                        <button type="button"><img id='searchImg' src="https://d2.naver.com/static/img/app/spr_btn_search.png"></button>
                    </div>
                </div>
            </div>

        </header>
        {% block content %}

        {% endblock %}
        <footer>
            <div id="footerBox">
                <div id="inner_box">
                    <ul class="other_site">
                        <li><a href="https://developers.naver.com/main/" id="developers">Naver Developers</a></li>
                        <li><a href="https://techcon.naver.com/" id="techcon">techcon</a></li>
                        <li><a href="https://deview.kr/2020" id="deview">deview</a></li>
                        <li><a href="https://naver.github.io/" id="github">github</a></li>
                        <li><a href="http://www.d2startup.com/" id="d2startup"></a></li>
                    </ul>
                    <div id="sns_share">
                        <ul>
                            <li id="email"><a href="mailto:d2@navercorp.com"><i class="xi-mail"></i></a></li>
                            <li id="facebook"><a href="https://www.facebook.com/naverd2"><i class="xi-facebook"></i></a></li>
                            <li id="rss"><a href="https://d2.naver.com/d2.atom"><i class="xi-rss"></i></a></li>
                        </ul>
                    </div>
                </div>
                <div id="footer_sec">
                    <div id="copyright">
                        <p>
                            <span>Copyright</span> &copy;<a href="https://www.navercorp.com">
                            Naver Corp.
                        </a>
                            <span>All Rights Reserved.</span>
                        </p>
                    </div>
                </div>
            </div>
        </footer>
    </div><!-- wrap 끝 -->
</body>
</html>

templates/main/program.html
{% extends "main/layout.html" %}

{% block content %}
    <section>
        <article id="show">
             <div id="showProMain">
                <p id="proTitle">
                    D2 Program
                    <span id="bar">&nbsp;</span>
                    <span id="proTitleText">
                        가치 있는 기술 지식 생산을 돕고, 경험을 나누며, 개발자를 지원합니다.
                    </span>
                </p>
             </div>
        </article>
        <article id="content" align="center">
            <div id="contentBox">
                <div class="deview" >
                    <div id="deviewImg" ><img src="https://d2.naver.com/static/img/app/img_deview.png"></div>
                    <div id="deviewText" align="left">
                        <strong align="left"></strong>
                        <p>지식을 나누고 탁월함을 추구하며, 함께 성장하는 대한민국 대표 개발자 컨퍼런스</p>
                        <a target ="_blank" id="site1"  style="cursor:pointer;">

                            <span>사이트 바로가기</span>
                        </a>
                    </div>
                </div>
                <div class="techConcert">
                    <div id="techImg"><img src="https://d2.naver.com/static/img/app/img_techconcert.png"></div>
                    <div id="techText" align="left">
                        <strong>Tech Concert</strong>
                        <p>주제별 기술 공유 세미나로 다양한 기술 이야기와 개발 경험을 직접 들을 수 있는 자리입니다.</p>
                        <a target ="_blank" id="site2" style="cursor:pointer;">
                            <span>사이트 바로가기</span>
                        </a>
                    </div>
                </div>
                <div class="campusFest">
                    <div id="campusFestImg"><img src="https://d2.naver.com/static/img/app/img_fest.png"></div>
                    <div id="FestText" align="left">
                        <strong>CAMPUS FEST</strong>
                        <p>대학생을 위한 오픈소스 SW 경진대회로 자신의 아이디어를 다른사람과 함께 나누고,</p>
                        <p>서로의 소스코드에 기여할 수 있는 기회를 제공합니다. 대학생들에 의해 더 많은 오픈소스</p>
                        <p>SW가 만들어지고 활용되기를 기대합니다.</p>
                        <a target ="_blank" id="site3" style="cursor:pointer;">
                            <span>사이트 바로가기</span>
                        </a>
                    </div>
                </div>
                <div class="d2_Campus">
                    <div id="d2CampusImg"><img src="https://d2.naver.com/static/img/app/img_partner.png"></div>
                    <div id="campusText" align="left">
                        <strong>D2 CAMPUS</strong>
                        <p>다른 학생 개발자에게 개발 지식을 공유할 수 있도록 실력있는 SW 동아리, 소모임, 학회,</p>
                        <p>세미나, 컨퍼런스를 지원합니다. 해당 결과물은 D2 채널을 통해 공유하고 있습니다.</p>
                        <a target ="_blank" id="site4" style="cursor:pointer;">
                            <span>사이트 바로가기</span>
                        </a>
                    </div>
                </div>
                <div class="community">
                    <div id="communityImg"><img src="https://d2.naver.com/static/img/app/img_community.png"></div>
                    <div id="communityText" align="left">
                        <strong>D2 COMMUNITY</strong>
                        <p>개발자 커뮤니티 활동이 활발하게 진행될 수 있도록 필요한 사항들을 지원하고</p>
                        <p>커뮤니티에서 만들어진 결과물이 외부 개발자들에게 쉽게 공유될 수 있는 기반을 마련하기</p>
                        <p>위해 진행하는 지원 프로그램입니다.</p>
                        <a target ="_blank" id="site5" style="cursor:pointer;">
                            <span>사이트 바로가기</span>
                        </a>
                    </div>
                </div>
            </div>
        </article>
    </section>

{% endblock %}