accounts/urls.py
from django.urls import path
from .views import *

app_name = 'accounts'

urlpatterns = [
    path('signup/', signup, name='signup'),
    path('login/', login_check, name='login'),
    path('logout/', logout, name='logout'),
]

community/urls.py
from django.urls import path
from .views import *

app_name = 'community'

urlpatterns = [
    path('', forum, name='forum'),
    path('<int:question_id>', detail, name='detail'),
    path('answer/create/<int:question_id>',  answer_create, name='answer_create'),
    path('question/create/', question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_delete, name='question_delete'),
    path('answer/modify/<int:answer_id>/', answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_delete, name='answer_delete')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from main.views import index, program

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('program/', program, name='program'),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('community/', include('community.urls')),
]

community/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    # Question Field에 author 필드 추가 (회원 아이디)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    # 수정 날짜 Field 추가
    modify_date = models.DateTimeField(null=True, blank=True)
    # 조회수 기능
    n_hit = models.PositiveIntegerField(default=0)

    @property
    def update_counter(self):
        self.n_hit = self.n_hit + 1
        self.save()

    def __str__(self):
        return self.subject


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    # 수정 날짜 필드 추가 (null 허용, form.is_valid() 검사 시 빈 값 허용
    modify_date = models.DateTimeField(null=True, blank=True)

community/forms.py
from django import forms
from community.models import Question, Answer

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        lables = {
            'content': '답변내용',
        }

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['subject', 'content']

        labels = {
            'subject': '제목',
            'content': '내용',
        }

community/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Question, Answer
from django.utils import timezone
from .forms import QuestionForm, AnswerForm
from django.core.paginator import Paginator
from django.contrib import messages

# Create your views here.

def forum(request):
    '''
    forum 목록 출력
    '''
    page = request.GET.get('page', '1')
    question_list = Question.objects.order_by('-create_date')

    paginator = Paginator(question_list, 10)
    page_obj = paginator.get_page(page)

    context = {'question_list': page_obj}

    return render(request, 'community/forum.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'community/forum_detail.html', context)


def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.create_date = timezone.now()
            answer.question = question
            answer.author = request.user # author 적용
            answer.save()
            return redirect('community:detail', question_id=question.id)

    else:
        form = AnswerForm()
    context = {'question': question, 'form': form}
    return render(request, 'community/forum_detail.html', context)


def question_create(request):
    if request.method == "POST":
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.create_date = timezone.now()
            question.author = request.user
            question.save()
            return redirect('/community')
    else:
        form = QuestionForm()
    context = {'form': form}
    return render(request, 'community/forum_question_form.html', context)

def question_modify(request, question_id):
    '''
    community 질문 수정
    '''

    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '수정권한이 없습니다.')
        return redirect('community:detail', question_id=question.id)

    if request.method == 'POST':
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.modify_date = timezone.now()
            question.save()
            return redirect('community:detail', question_id=question.id)

    else:
        form = QuestionForm(instance=question)
    context = {'form': form}
    return render(request, 'community/forum_question_form.html', context=context)


def question_delete(request, question_id):
    '''
    qustion 삭제 기능
    '''
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '삭제권한이 없습니다.')
        return redirect('community:detail', question_id=question.id)

    question.delete()
    return redirect('community:forum')

def answer_modify(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '수정권한이 없습니다.')
        return redirect('community:detail', question_id=answer.question.id)

    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.modify_date = timezone.now()
            answer.save()
            return redirect('community:detail', question_id=answer.question.id)

    else:
        form = AnswerForm(instance=answer)
    context = {'answer': answer, 'form': form}
    return render(request, 'community/answer_form.html', context)

def answer_delete(request, answer_id):
    """
    답변삭제
    """
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '삭제권한이 없습니다.')
    else:
        answer.delete()
    return redirect('community:detail', question_id=answer.question.id)

templates/community/answer_form.html
{% extends 'community/forum_layout.html' %}

{% block content %}
<div class="container my-3">
    <form id='answer_form' method="post" class="my-3" >
        {% csrf_token %}
        <div class="form-group">
            <textarea name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <button type="submit" class="btn border float-right">새 댓글</button>
    </form>
</div>
{% endblock %}

templates/community/forum.html
{% extends 'community/forum_layout.html' %}
{% load combot_filter %}

{% block content %}

<!--    http://서버주소/combot/question_create -->

<div class="container my-3">
    <div id="new_question_btn">
        {% if user.is_authenticated %}
        <button onclick="location.href='{% url 'community:question_create' %}'" class="btn border float-right"> <span><i class="xi-plus"></i> 새 글쓰기</span></button>
        {% else %}
        <button onclick="location.href='{% url 'accounts:login' %}'" class="btn border float-right"> <span><i class="xi-plus"></i> 새 글쓰기</span></button>
        {% endif %}
    </div>
    <!--    <a href="{% url 'community:question_create' %}" class="btn btn-primary float-right">질문 등록하기</a>-->
<!-- m : margin p : padding -->
    {% if question_list %}
    {% for question in question_list %}
    <div id='question_list' class="border-0">
        <div class="card my-3 text-left bg-white">
            <div class="card-header bg-white border-0 my-3">
                <a href="{% url 'community:detail' question.id %}"><h3>{{question.subject}}<span class="float-right"><i class="xi-eye">  {{question.n_hit}}</i></span></h3>
            </div>
            <div class="card-body my-3">
                <a href="{% url 'community:detail' question.id %}">{{question.content|mark}}</a>
            </div>
            <div class="card-footer bg-white border-0 my-3">
                <span> 작성자 : {{question.author}}</span><span>|</span><span>작성일 : {{question.create_date}}</span>
            </div>
        </div>
    </div>
    {% endfor %}
    {% else %}
    <div id='question_list' class="container my-3 border-0">
        <div class="card my-3 text-left bg-white">
            질문이 없습니다.
        </div>
    </div>
    {% endif %}

<!-- 페이징처리 시작 -->
    <ul id='paginator' class="pagination justify-content-center">
        <!-- 이전페이지 출력 -->
        {% if question_list.has_previous %} <!-- 현재 페이지 기준으로 이전 페이지가 있으면 -->
        <li class="page-item">
            <a class="page-link" href="?page={{ question_list.previous_page_number }}">이전</a>
        </li>
        {% else %} <!-- 이전 페이지가 없는 경우 -->
<!--        <li class="page-item disabled">-->
<!--            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>-->
<!--        </li>-->
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in question_list.paginator.page_range %} <!-- 총 베이지 번호 만큼 for loop 실행 -->
        {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
            <!-- 새로 구성될 페이지 번호가 현재페이지 기준으로 크면 5만큼 작은 값만 표시 and
            현재 페이지 기준으로 작으면 5만큼 큰값만 표시 -->
            {% if page_number == question_list.number %} <!-- 마지막 페이지인지 여부 -->
            <li id='current_page' class="page-item active" aria-current="page">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음 페이지 -->
        {% if question_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ question_list.next_page_number }}"><i class="xi-angle-right"></i></a>
        </li>
        {% else %}
<!--        <li class="page-item disabled">-->
<!--            <a class="page-link" tabindex="-1" aria-disabled="true" href="#"><i class="xi-angle-right"></i></a>-->
<!--        </li>-->
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
</div>
{% endblock %}

templates/community/forum_detail.html
{% extends 'community/forum_layout.html' %}
{% load combot_filter %}

{% block content %}
{{ question.update_counter }}

<div id='question_detail' class="container my-3">
    <h2 class="border-bottom py-2">{{ question.subject }}
<!--        로그인 한 유저와 작성자가 같으면 수정 버튼 보이도록 조건문 추가-->
        {% if request.user == question.author %}
        <span id='edit' class="float-right py-2">
            <i onclick="location.href='{% url 'community:question_modify' question.id %}'" class="xi-pen-o"></i>
            <i class="xi-trash-o delete" data-uri="{% url 'community:question_delete' question.id %}"></i>
        </span>
        {% endif %}
    </h2>
    <div class="card my-3">
        <div class="card-header text-left bg-white border-bottom-0">
            <span>{{ question.author }}</span><span>{{ question.create_date }}</span>
        </div>
        <div class="card-body">
            <div class="card-text">
                {{ question.content|mark}}
            </div>
        </div>
    </div>

    <h4 class="border-bottom text-left my-3 py-2"> 댓글 <span>{{question.answer_set.count}}</span></h4>
    <!-- 답변출력 -->
    {% for answer in question.answer_set.all %}
    <div class="card my-3">
        <div id="answer" class="card-header text-left bg-white border-bottom-0">
            <span>{{ answer.author }}</span><span>{{ answer.create_date }}</span>
            {% if request.user == answer.author %}
            <span class="float-right">
                <i onclick="location.href='{% url 'community:answer_modify' answer.id %}'" class="xi-pen-o"></i>
                <i data-uri="{% url 'community:answer_delete' answer.id %}" class="xi-trash-o delete"></i>
            </span>
            {% endif %}
        </div>
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">
                {{ answer.content|mark }}
            </div>
        </div>
    </div>
    {% endfor %}

<!-- 답변등록 form 생성 -->
    <form id='answer_form' action="{% url 'community:answer_create' question.id %}" method="post" class="my-3" >
        {% csrf_token %}
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
        {% for field in form %}
        {% if field.errors %}
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
        {% endif %}
        {% endfor %}
        </div>
        {% endif %}

        {% if user.is_authenticated %}
            <div class="form-group">
                <textarea name="content" id="content" class="form-control" rows="10"></textarea>
            </div>
            <button type="submit" class="btn border float-right">새 댓글</button>
        </form>
        {% else %}
            <div class="form-group">
                <textarea placeholder="로그인 후 이용해주세요." class="form-control" rows="10" disabled=""></textarea>
            </div>
        </form>
        <button onclick="location.href='{% url 'accounts:login' %}'" title="로그인 후 이용해주세요." class="btn border float-right"> 로그인 후 댓글 쓰기</button>
        {% endif %}
</div>
{% endblock %}


<!-- script block-->
{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".delete").on('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });
});
</script>
{% endblock %}

templates/community/forum_question_form.html
{% extends 'community/forum_layout.html' %}

{% block content %}
<div class="container" id="question_enroll">
    <h3 class="my-4 border-bottom pb-4 text-left">Forum > 새 글 쓰기</h3>
    <form method="post" class="form-horizontal">
        {% csrf_token %}
<!--        \{\{form.as_p\}\}-->
        <!-- 오류 표시 : 입력칸에 어떤 입력도 없이 저장하면 -->
        {% if form.errors %}
            <div class="alert alert-danger" role="alert">
                {% for field in form %}
                    {% if field.errors %}
                        <strong>{{field.label}}</strong>
                        {{field.errors}}
                    {% endif %}
                {% endfor %}
            </div>
        {% endif %}
        <!-- 오류 처리 끝 -->
        <!-- 질문 등록 폼 -->
        <div id='enroll' class="form-inline form-group my-4 pb-3 border-bottom">
            <label for="subject" class="control-label col-sm-2 text-left">제목 : </label>
            <div class="col-sm-10" id="question_title">
                <input type="text" class="form-control" name="subject" id="subject"
                       value="{{form.subject.value|default_if_none:''}}">
                        <!-- value는 form의 subject의 value를 보내고, 아무것도 작성하지 않은 경우 원래 None 값을 보내는데 그 대신 빈 값을 보냄
                            한번 입력 후에 오류로 인해서 다시 입력화면으로 넘어오면 기존 입력값을 유지해줌-->
            </div>
        </div>
        <div class="form-group my-6">
<!--            <label for="content">내용</label>-->
            <textarea class="form-control" name="content" id="content" rows="10" value="{{form.content.value|default_if_none:''}}"></textarea>
        </div>
        <button type="submit" class="btn border float-right">새글 쓰기</button>
    </form>
</div>
{% endblock %}